{% set name = "scriptconfig" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scriptconfig-{{ version }}.tar.gz
  sha256: 4d01a4e3198e7efc049af0446662cedf97d5153d208818a87b76ea9fa654e008

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=41.0.1
  run:
    - python >={{ python_min }}
    - pyyaml
    - ubelt >=1.3.6

test:
  imports:
    - scriptconfig
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.kitware.com/utils/scriptconfig/
  summary: Easy dict-based script configuration with CLI support
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Erotemic
    - vicentebolea
